// Generates the parameter plumbing from the parameter table:
//   dsp/ParamStore.cmajor  - the 342 parameter endpoints (named after the original skin actions),
//                            forwarding every change to the synth as (slot, value)
//   dsp/Slots.cmajor       - slot constants: index into the synth's mirror of the program struct
//   tools/test/build/fields_gen.h - endpoint -> chunk field table for the C++ test host
//
// run: node tools/gen.mjs

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { FIELDS } from "../ui/oatmeal/fields.js";
import { paramInfo } from "../ui/paraminfo.js";

const root = join (dirname (fileURLToPath (import.meta.url)), "..");

// The synth mirrors the program struct as float P[NUM_SLOTS], slot = chunk offset / 4.
// Filter 1 and filter 2 share one int in the chunk; they get their own virtual slots.
export const NUM_SLOTS = 2600;
const VIRTUAL = { filter1: 2594, filter2: 2595 };

function slotOf (f)
{
    const [, , , off, type] = f;
    if (type === "filter1" || type === "filter2") return VIRTUAL[type];
    return off / 4;
}

function cmajString (s) { return JSON.stringify (s); }

function num (x)
{
    if (Number.isInteger (x)) return String (x);
    let s = String (Math.fround (x));
    if (! /[.e]/.test (s)) s += ".0";
    return s;
}

const endpoints = [], handlers = [], slots = [], cfields = [];

for (const f of FIELDS)
{
    const [index, id, name, off, type] = f;
    const info = paramInfo (index);
    const slot = slotOf (f);
    const isInt = type === "i32" || type === "filter1" || type === "filter2";
    const ann = [`name: ${cmajString (info.hostName)}`];

    if (isInt)
    {
        ann.push (`min: ${info.min | 0}`, `max: ${info.max | 0}`, `init: ${Math.round (info.init)}`);
        if (info.names) ann.push (`text: ${cmajString (info.names.join ("|"))}`);
        else ann.push (`step: 1`);
        endpoints.push (`    input event int ${id} [[ ${ann.join (", ")} ]];`);
        handlers.push (`    event ${id} (int v) { paramOut <- porridge::ParamChange (${slot}, float (v)); }`);
    }
    else
    {
        ann.push (`min: ${num (info.min)}`, `max: ${num (info.max)}`, `init: ${num (info.init)}`);
        if (info.unit) ann.push (`unit: ${cmajString (info.unit)}`);
        endpoints.push (`    input event float ${id} [[ ${ann.join (", ")} ]];`);
        handlers.push (`    event ${id} (float v) { paramOut <- porridge::ParamChange (${slot}, v); }`);
    }

    slots.push (`    let ${id} = ${slot};`);
    cfields.push (`    { "${id}", ${off}, FieldType::${type} },`);
}

const header = `//  Generated by tools/gen.mjs - do not edit by hand.\n\n`;

writeFileSync (join (root, "dsp", "ParamStore.cmajor"), header +
`/// Every parameter of the original, in the original order, as an endpoint named after the
/// original skin action. Values are the internal values stored in an Oatmeal preset.
/// Each change is forwarded to the synth as (slot, value).
processor ParamStore
{
    output event porridge::ParamChange paramOut;

${endpoints.join ("\n")}

${handlers.join ("\n")}
}
`);

writeFileSync (join (root, "dsp", "Slots.cmajor"), header +
`namespace porridge
{
    /// A parameter change: slot = chunk offset / 4 (or a virtual slot), value = internal value.
    struct ParamChange
    {
        int slot;
        float value;
    }

    let numSlots = ${NUM_SLOTS};
}

/// Index of every parameter in the synth's mirror of the program struct.
namespace porridge::slot
{
${slots.join ("\n")}
}
`);

mkdirSync (join (root, "tools", "test", "build"), { recursive: true });
writeFileSync (join (root, "tools", "test", "build", "fields_gen.h"), header.replace (/\/\//g, "//") +
`#pragma once
enum class FieldType { f32, i32, filter1, filter2, pw };
struct PorridgeField { const char* id; int offset; FieldType type; };
static const PorridgeField porridgeFields[] =
{
${cfields.join ("\n")}
};
`);

console.log (`generated ${FIELDS.length} parameters`);
