// Builds the sound matcher's engine (ui/match/): the synth compiled to WebAssembly, which the
// matcher's workers render candidate patches with, off the plugin's audio thread.
//
//  - build/match/ gets a copy of the patch's DSP in which the effects rack holds one of each
//    effect instead of up to four (dsp/Slots.cmajor's rack counts; the rack's code indexes
//    them with .at(), which wraps). The matcher leaves the rack empty, and one instance's
//    state goes from 68 MB to 38 MB.
//  - `cmaj generate --target=javascript --simd-only` turns it into a JavaScript class with the
//    WebAssembly inside it, which is split into
//      bundle/match-engine.wasm  the module, which the view compiles once for all its workers
//      bundle/match-engine.js    the class (a plain script that declares PorridgeMatchEngine),
//                                given the compiled module as `wasmModule` before initialise()
//
// It takes about half a minute, so it is skipped when the DSP hasn't changed since the last
// build (build/match/inputs.json). The manifest lists both files as resources; the view
// fetches them the first time someone matches a sound.
//
//   node tools/match-engine.mjs [--force]

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join (dirname (fileURLToPath (import.meta.url)), "..");
const out = join (root, "build", "match");
const bundle = join (root, "bundle");
const cmaj = process.env.CMAJ ?? "cmaj";
const name = "PorridgeMatchEngine";

const { source } = JSON.parse (readFileSync (join (root, "Porridge.cmajorpatch"), "utf8"));
const sources = source.filter (s => ! s.endsWith ("Porridge.cmajor"));

// The graph: the parameters, MIDI and the waveforms in, the audio out.
const graph = `//  Generated by tools/match-engine.mjs - do not edit by hand.
//  The sound matcher's engine: Porridge's synth without its view outputs.

graph ${name}  [[ main ]]
{
    input params.*;

    input event std::midi::Message midiIn;
    input event porridge::Shape shapeIn;
    input event porridge::Curve curveIn;

    output stream float<2> out;

    node params = ParamStore;
    node synth  = porridge::Synth;

    connection
    {
        params.paramOut -> synth.paramIn;
        midiIn          -> synth.midiIn;
        shapeIn         -> synth.shapeIn;
        curveIn         -> synth.curveIn;
        synth.out       -> out;
    }
}
`;

const files = new Map (sources.map (s => {
    const text = readFileSync (join (root, s), "utf8");
    return [s, s.endsWith ("Slots.cmajor") ? text.replace (/^(    let [a-z]+Count = )\d+;/gm, "$11;") : text];
}));

const hash = createHash ("sha256");
hash.update (readFileSync (fileURLToPath (import.meta.url)));
for (const [s, text] of files) hash.update (s + "\0" + text);
const inputs = hash.digest ("hex");

const stamp = join (out, "inputs.json");
const wasmPath = join (bundle, "match-engine.wasm");
const jsPath = join (bundle, "match-engine.js");
const upToDate = existsSync (stamp) && existsSync (wasmPath) && existsSync (jsPath)
                 && JSON.parse (readFileSync (stamp, "utf8")).inputs === inputs;

if (upToDate && ! process.argv.includes ("--force"))
{
    console.log ("bundle/match-engine.{js,wasm} are up to date");
    process.exit (0);
}

mkdirSync (join (out, "dsp"), { recursive: true });
mkdirSync (bundle, { recursive: true });
for (const [s, text] of files) writeFileSync (join (out, s), text);
writeFileSync (join (out, `${name}.cmajor`), graph);
writeFileSync (join (out, `${name}.cmajorpatch`), JSON.stringify ({
    CmajorVersion: 1,
    ID: "dev.porridge.match",
    version: "1.0",
    name,
    isInstrument: true,
    source: [...sources, `${name}.cmajor`],
}, null, 4));

const generated = join (out, "generated.js");
console.log ("generating the matcher's engine (about half a minute)...");
execFileSync (cmaj, ["generate", "--target=javascript", "--simd-only", `--output=${generated}`, join (out, `${name}.cmajorpatch`)],
              { stdio: ["ignore", "ignore", "inherit"] });

let js = readFileSync (generated, "utf8").replace (/\r\n/g, "\n");

const fail = what => { throw new Error (`match-engine: ${what} in the generated class; has Cmajor's JavaScript output changed?`); };

// Cmajor writes a SIMD and a plain build whatever --simd-only says; the plain one goes (every
// web view the plugin runs in has SIMD). The private methods each start with this header.
const method = name => `  /** @access private */\n  ${name}`;
const at = name =>
{
    const i = js.indexOf (method (name));
    if (i < 0) fail (`no ${name}`);
    return i;
};
js = js.slice (0, at ("async _initialiseInternalNonSIMD")) + js.slice (at ("_getWasmBytesSIMD()"));

// The module's bytes are a literal in the last methods; they become the .wasm file.
const bytes = /^  _getWasmBytesSIMD\(\)\n  \{\n    return new Uint8Array\(\[([\d,\s]*)\]\);/m.exec (js.slice (at ("_getWasmBytesSIMD()")));
if (! bytes) fail ("no WebAssembly bytes");
const wasm = Uint8Array.from (bytes[1].split (",").map (s => s.trim()).filter (s => s !== "").map (Number));
js = js.slice (0, at ("_getWasmBytesSIMD()")) + "}\n";

// The class instantiates the module the view compiled (WebAssembly.instantiate gives an
// Instance for a Module, rather than { module, instance } for bytes).
const replaceOnce = (find, replacement) =>
{
    if (js.split (find).length !== 2) fail (`not one ${JSON.stringify (find)}`);
    js = js.replace (find, replacement);
};
replaceOnce ("await this._initialiseInternalNonSIMD (sessionID, frequency);", `throw new Error ("this system's WebAssembly has no SIMD");`);
replaceOnce ("await WebAssembly.instantiate (this._getWasmBytesSIMD(), imports);", "await WebAssembly.instantiate (this.wasmModule, imports);");
replaceOnce ("this.instance = result.instance;", "this.instance = result.instance ?? result;");

writeFileSync (wasmPath, wasm);
writeFileSync (jsPath, `// Generated by tools/match-engine.mjs from Cmajor's JavaScript output - do not edit by hand.\n${js}`);
writeFileSync (stamp, JSON.stringify ({ inputs }));
console.log (`${name} -> bundle/match-engine.wasm (${(wasm.length / 1e6).toFixed (2)} MB), bundle/match-engine.js (${(js.length / 1e6).toFixed (2)} MB)`);
